### ISSUE TITLE
Exact matches are case-sensitive

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/open-register-of-interests#15]
If I do a search for "boris", then click "advanced", then select "Member name" "contains exactly" "johnson", I get no results. If I change the filter to "Johnson", I get the results I expect. 

I'd prefer exact match to be case-insensitive, but I'd know what to do if the UI just announced that it's case-sensitive.

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix UI issues](https://trello.com/c/yarURTrd/113-fix-ui-issues)

**Comment by Bjwebb** [comment]
This should be fixed on http://dev.oroi-proxy.docker.opendataservices.uk0.bigv.io/
