### ISSUE TITLE
Clicking the big title i'd expect to reset search and take me 'home'

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/open-register-of-interests#17]

**Comment by Bjwebb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix UI issues](https://trello.com/c/yarURTrd/113-fix-ui-issues)

**Comment by Bjwebb** [comment]
This should be fixed on http://dev.oroi-proxy.docker.opendataservices.uk0.bigv.io/
